## Camera

# Config
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
#set_property CONFIG_MODE SPIx4 [current_design]
#set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]

# 50MHz Clock
set_property PACKAGE_PIN G11 [get_ports CLK50_I]
set_property IOSTANDARD LVCMOS33 [get_ports CLK50_I]
create_clock -period 20.000 -name CLK50_I -waveform {0.000 10.000} [get_ports {CLK50_I}]

# Flash SPI (BANK14, HR, 3.3V)
set_property PACKAGE_PIN C11 [get_ports FLASH_CS_O]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_CS_O]
#set_property PACKAGE_PIN A8 [get_ports {FLASH_SCK_O}]		#CCLK Pin not directly available
#set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_SCK_O}]
set_property PACKAGE_PIN B11 [get_ports {FLASH_DQ_IO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_DQ_IO[0]}]
set_property PACKAGE_PIN B12 [get_ports {FLASH_DQ_IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_DQ_IO[1]}]
set_property PACKAGE_PIN D10 [get_ports {FLASH_DQ_IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_DQ_IO[2]}]
set_property PACKAGE_PIN C10 [get_ports {FLASH_DQ_IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_DQ_IO[3]}]

# LED on FPGA Module
set_property PACKAGE_PIN M10 [get_ports LED_O]
set_property IOSTANDARD LVCMOS33 [get_ports LED_O]

# Ethernet PHY (BANK14, 3.3V)
set_property PACKAGE_PIN E11 [get_ports {PHY_LED_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_LED_O}]

#set_property PACKAGE_PIN D14 [get_ports {PHY_CLK_I}]
#set_property IOSTANDARD LVCMOS33 [get_ports {PHY_CLK_I}]

set_property PACKAGE_PIN P13 [get_ports {PHY_RST_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RST_O}]

set_property PACKAGE_PIN P12 [get_ports {PHY_INT_PD_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_INT_PD_O}]

set_property PACKAGE_PIN B14 [get_ports {PHY_MDC_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_MDC_O}]
set_property PACKAGE_PIN B13 [get_ports {PHY_MD_IO}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_MD_IO}]

set_property PACKAGE_PIN H11 [get_ports {PHY_TXCK_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TXCK_O}]
set_property PACKAGE_PIN N11 [get_ports {PHY_TXCTL_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TXCTL_O}]
set_property PACKAGE_PIN H14 [get_ports {PHY_TXERR_O}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TXERR_O}]

set_property PACKAGE_PIN H12 [get_ports {PHY_TX_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[0]}]
set_property PACKAGE_PIN F12 [get_ports {PHY_TX_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[1]}]
set_property PACKAGE_PIN G14 [get_ports {PHY_TX_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[2]}]
set_property PACKAGE_PIN E12 [get_ports {PHY_TX_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[3]}]
set_property PACKAGE_PIN F14 [get_ports {PHY_TX_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[4]}]
set_property PACKAGE_PIN D12 [get_ports {PHY_TX_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[5]}]
set_property PACKAGE_PIN E13 [get_ports {PHY_TX_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[6]}]
set_property PACKAGE_PIN F13 [get_ports {PHY_TX_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TX_O[7]}]

set_property PACKAGE_PIN H13 [get_ports {PHY_RXCK_I}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RXCK_I}]
set_property PACKAGE_PIN N10 [get_ports {PHY_RXCTL_I}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RXCTL_I}]
set_property PACKAGE_PIN P11 [get_ports {PHY_RXERR_I}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RXERR_I}]

set_property PACKAGE_PIN J14 [get_ports {PHY_RX_I[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[0]}]
set_property PACKAGE_PIN J12 [get_ports {PHY_RX_I[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[1]}]
set_property PACKAGE_PIN J13 [get_ports {PHY_RX_I[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[2]}]
set_property PACKAGE_PIN J11 [get_ports {PHY_RX_I[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[3]}]
set_property PACKAGE_PIN L14 [get_ports {PHY_RX_I[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[4]}]
set_property PACKAGE_PIN N14 [get_ports {PHY_RX_I[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[5]}]
set_property PACKAGE_PIN M14 [get_ports {PHY_RX_I[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[6]}]
set_property PACKAGE_PIN M13 [get_ports {PHY_RX_I[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RX_I[7]}]

# Sensor (BANK 34, 1.8V (or 3.3V)
# Debug pins
set_property PACKAGE_PIN P5 [get_ports {DBG_O[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DBG_O[0]}]
set_property PACKAGE_PIN N4 [get_ports {DBG_O[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DBG_O[1]}]

# Clock
set_property PACKAGE_PIN H4 [get_ports {SENS_CLOCK_I}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_CLOCK_I}]

# DVAL
set_property PACKAGE_PIN B5 [get_ports {SENS_DVAL_I}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DVAL_I}]

# SPI
set_property PACKAGE_PIN A3 [get_ports {SENS_CS_O}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_CS_O}]
set_property PACKAGE_PIN B1 [get_ports {SENS_SCK_O}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_SCK_O}]
set_property PACKAGE_PIN A2 [get_ports {SENS_MISO_I}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_MISO_I}]
set_property PACKAGE_PIN B3 [get_ports {SENS_MOSI_O}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_MOSI_O}]

# Enable
set_property PACKAGE_PIN C3 [get_ports {SENS_EN_O}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_EN_O}]

# GPIO
set_property PACKAGE_PIN A5 [get_ports {SENS_GP_IO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_GP_IO[0]}]
set_property PACKAGE_PIN A4 [get_ports {SENS_GP_IO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_GP_IO[1]}]
set_property PACKAGE_PIN B6 [get_ports {SENS_GP_IO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_GP_IO[2]}]

# Data
set_property PACKAGE_PIN B2 [get_ports {SENS_DATA_I[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[0]}]
set_property PACKAGE_PIN C4 [get_ports {SENS_DATA_I[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[1]}]
set_property PACKAGE_PIN D4 [get_ports {SENS_DATA_I[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[2]}]
set_property PACKAGE_PIN C1 [get_ports {SENS_DATA_I[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[3]}]
set_property PACKAGE_PIN E4 [get_ports {SENS_DATA_I[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[4]}]
set_property PACKAGE_PIN D1 [get_ports {SENS_DATA_I[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[5]}]
set_property PACKAGE_PIN E2 [get_ports {SENS_DATA_I[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[6]}]
set_property PACKAGE_PIN D2 [get_ports {SENS_DATA_I[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[7]}]

set_property PACKAGE_PIN C5 [get_ports {SENS_DATA_I[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[8]}]
set_property PACKAGE_PIN F2 [get_ports {SENS_DATA_I[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[9]}]
set_property PACKAGE_PIN F1 [get_ports {SENS_DATA_I[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[10]}]
set_property PACKAGE_PIN G1 [get_ports {SENS_DATA_I[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[11]}]
set_property PACKAGE_PIN F4 [get_ports {SENS_DATA_I[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[12]}]
set_property PACKAGE_PIN F3 [get_ports {SENS_DATA_I[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[13]}]
set_property PACKAGE_PIN H3 [get_ports {SENS_DATA_I[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[14]}]
set_property PACKAGE_PIN G4 [get_ports {SENS_DATA_I[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[15]}]

set_property PACKAGE_PIN J4 [get_ports {SENS_DATA_I[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[16]}]
set_property PACKAGE_PIN J3 [get_ports {SENS_DATA_I[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[17]}]
set_property PACKAGE_PIN K3 [get_ports {SENS_DATA_I[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[18]}]
set_property PACKAGE_PIN J1 [get_ports {SENS_DATA_I[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[19]}]
set_property PACKAGE_PIN J2 [get_ports {SENS_DATA_I[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[20]}]
set_property PACKAGE_PIN M1 [get_ports {SENS_DATA_I[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[21]}]
set_property PACKAGE_PIN L1 [get_ports {SENS_DATA_I[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[22]}]
set_property PACKAGE_PIN M3 [get_ports {SENS_DATA_I[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[23]}]

set_property PACKAGE_PIN K4 [get_ports {SENS_DATA_I[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[24]}]
set_property PACKAGE_PIN L2 [get_ports {SENS_DATA_I[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[25]}]
set_property PACKAGE_PIN M2 [get_ports {SENS_DATA_I[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[26]}]
set_property PACKAGE_PIN P3 [get_ports {SENS_DATA_I[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[27]}]
set_property PACKAGE_PIN L3 [get_ports {SENS_DATA_I[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[28]}]
set_property PACKAGE_PIN N1 [get_ports {SENS_DATA_I[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[29]}]
set_property PACKAGE_PIN P2 [get_ports {SENS_DATA_I[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[30]}]
set_property PACKAGE_PIN P4 [get_ports {SENS_DATA_I[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SENS_DATA_I[31]}]
